### ISSUE TITLE
Classic wallet doesn't work

### ISSUE THREAD

**Issue by arvicco** [ethereumclassic/etherwallet#14]
As reported here: https://www.reddit.com/r/EthereumClassic/comments/5epag2/classicetherwallet_does_not_work/

ClassicEtherWallet (https://elaineo.github.io/etherwallet) does not work! When sending any ETC amount and at any ETC address appears one and the same mistake - "Error: Transaction fee is too low. There is another transaction with same nonce in the queue. Try increasing the fee or incrementing the nonce." Developers can see this wallet and check what is the problem?

**Comment by realcodywburns** [comment]
The problem might be with the default  gas limit is still being set at 21000. This is too low for the current network. Im looking into it.

**Comment by elaineo** [comment]
@realcodywburns  I think it might be due to a nonce increase when tx's were broadcast yesterday, then mined into orphaned blocks. I haven't found any addresses where this occurs though, do you have any?

**Comment by realcodywburns** [comment]
I'm trying to replicate the error. I am sending transactions through cew and waiting for the tx;s to hit the chain currently. My mist is showing a tx should be around .015 etc right now. That sounds way high.

**Comment by elaineo** [comment]
transactions were working for all the addresses I tested. I suspect that the person who ran into bugs was using an address that was involved in tx's during the network issues yesterday, so they were stuck with invalid tx's in the queue. I cleared out the pending tx's, hopefully that will work.

**Comment by ivannador** [comment]
I also experienced this problem, seems to be working now.

**Comment by whiteorg72** [comment]
I'm the person who reported the problem, just sent transaction with which address I had a problem, and now everything is working normally and the transaction went. 
UPDATE: Just tried to send a second transaction with the same address again the problem, TX ID transaction is formed, but the balance of coins will not be charged.
I tried to send a new third transaction with a new address, the exact same problem as in the second transaction, TX ID transaction is formed properly, but the coins from the address will not be charged and the transaction does not reach the destination address. So the problem remains.

**Comment by elaineo** [comment]
@whiteorg72 can you provide your address or tx hash? I can't really investigate this issue without any information about your transaction.

**Comment by whiteorg72** [comment]
@elaineo sent three addresses through your Twitter, those addresses which I used today, has passed only the first transaction 2 ETC, the other two transactions have not been as I reported here TX IDs have been formed properly, but the coins not are taken off from the balance sheet, so naturally they are not reached address.

**Comment by whiteorg72** [comment]
@elaineo Now is trying to send a fourth transaction (3 ETС) today, is also a problem that in other transactions hash is generated normally, and coins do not go away from the account and of course do not reach the account of the recipient. 
Transaction submitted. TX ID: 0x8a8e8f2ff1a0c6b2fb313c0087697a0bb3a66600853f94fd866ab2c1464067b4

**Comment by elaineo** [comment]
This seems to be an issue with Parity (possibly also geth), not the web wallet. Some tx's are created but never mined, and it sits in the pending transaction queue forever. I'll try to document this better later (unfortunately I won't be home until tonight) and reopen the issue under Parity.

**Comment by whiteorg72** [comment]
@elaineo Today I sent to the address (address number I have provided you previously) which previously had a problem, the transaction today was excellent.
