### ISSUE TITLE
any plan to rebase onto latest kvhnuke/mercury

### ISSUE THREAD

**Issue by hyugit** [ethereumclassic/etherwallet#15]
Hi All,

I noticed there are several new features in myetherwallet from kvhnuke. Is there any plan to rebase and get those features?

Much appreciated.

**Comment by elaineo** [comment]
@trave7er Which features are you interested in?

**Comment by interfect** [comment]
I for one need the ERC-20 token manipulation features. Also contract deployment would be incredibly useful.

**Comment by elaineo** [comment]
@interfect contract deployment added, ERC-20 in progress

**Comment by elaineo** [comment]
okay, ERC-20 support added
