### ISSUE TITLE
Compatibility with Cryptopia

### ISSUE THREAD

**Issue by psionin** [ethereumclassic/etherwallet#16]
I received a response from their support saying that deposits are registered based on the "send to" address, and since this wallet goes through a contract with a different address, there is an issue with tracking ETC deposits to their exchange. Any chance to have a version without the contract address proxy? (Maybe just saying "please don't use the forked version with this" would be sufficient.)

**Comment by elaineo** [comment]
@psionin you can avoid this by using the "send" function without replay protection
