### ISSUE TITLE
ClassicEtherWallet doesn't show balance nor allow transaction

### ISSUE THREAD

**Issue by ferdousbhai** [ethereumclassic/etherwallet#17]
Not sure if it's an issue with my particular wallet or it's a general issue with ClassicEtherWallet!
<img width="325" alt="screen shot 2016-12-27 at 5 15 45 am" src="https://cloud.githubusercontent.com/assets/23114244/21497439/dc8bddcc-cbf2-11e6-9891-8feeacc73b15.png">

**Comment by mikeyb** [comment]
Are you seeing any errors in the browser dev console? @ferdousbhai

**Comment by ferdousbhai** [comment]
Yes, the API doesn't seem to be working: 
POST https://classicetherwallet.com:8081/api net::ERR_INSECURE_RESPONSE

**Comment by mikeyb** [comment]
Thanks for the info.  This is happening on the Chrome Extension, correct?  If you go directly to https://classicetherwallet.com:8081/api do you see "OK" in your browser?  Might have been a temporary issue as I am able to hit the api page fine currently.  Is it working for you at this time?

**Comment by ferdousbhai** [comment]
I was able to make the transaction when using FireFox. Thanks for your help!
