### ISSUE TITLE
Problem to see balance

### ISSUE THREAD

**Issue by buytre** [ethereumclassic/etherwallet#21]
Hi,

Seens yesterday im trying to see my balance and always appears as "loading".
I sent to my wallet an ammount of ETC and at first a saw them, then a send some more and I couln't see them any more. Almoust 24 hours with this problem.

Thanks!

**Comment by elaineo** [comment]
can you try again now? it seems to be working. for some reason the server is seeing a lot of traffic these last few days, and is getting overloaded.

**Comment by buytre** [comment]
Thanks
