### ISSUE TITLE
Cant access my wallet

### ISSUE THREAD

**Issue by kavka3** [ethereumclassic/etherwallet#26]
Hello, 

I'm trying to access my wallet but without any success.
After I select my wallet file (keystore) and entered the password, pressing the button "unlock wallet", I got the message "Wallet successfully decrypted". but can't see any form to make the transactions.

![2017-05-12_113341](https://cloud.githubusercontent.com/assets/10809621/25990089/1dd07fe8-3707-11e7-9874-8e74bdbe08f2.jpg)

**Comment by hugozap** [comment]
You have to add a nickname to the wallet, then the "Add Wallet" Button will be visible and your wallet will be saved. I had the same issue. UI could be clearer here.
