### ISSUE TITLE
Account balance not updating on classicetherwallet.com

### ISSUE THREAD

**Issue by marinersouthampton** [ethereumclassic/etherwallet#27]
![account balance](https://cloud.githubusercontent.com/assets/28981981/26496549/e513e66c-421f-11e7-8e72-c35eed1053c1.PNG)
![etc](https://cloud.githubusercontent.com/assets/28981981/26496560/ed631e78-421f-11e7-9d6c-84875b217b7c.PNG)

Hi there, I have transferred few ETCs from Poloneix to classicetherwallet a few days back. The transaction was completed but somehow my Account balance on classicetherwallet doesnt update. It says LOADING and doesnt do anything. I can see them in the transaction history though. 

Please if you could guide me.

**Comment by elaineo** [comment]
`myetherwallet.com` is a different service, please contact them here: https://github.com/kvhnuke/etherwallet
