### ISSUE TITLE
Solde Caché

### ISSUE THREAD

**Issue by thibautdonald** [ethereumclassic/etherwallet#28]
Slt je n'arrive pas avoir mon solde du compte c'est toujours cacher c'est bizzare

**Comment by realcodywburns** [comment]
Le serveur auquel le portefeuille éther classique se connecte pour obtenir le solde se recharge parfois. Vous pouvez toujours vérifier votre équilibre sur l'un des explorateurs. Etcchain.com/explorer, gastracker.io et etherhub.io sont tous capables de fournir une balneure.
