### ISSUE TITLE
ETC sent but not received at exchange

### ISSUE THREAD

**Issue by iguanahk** [ethereumclassic/etherwallet#29]
ETC sent but not received at exchange

Will I get the funds back? If so, how long will that normally take?

Thanks

**Comment by undergroundbase** [comment]
Any feedback on this topic I have the same problem here is been 5 hours and nothing

**Comment by splix** [comment]
Is it related to Poloniex? Please contact their Support at https://poloniex.freshdesk.com/support/tickets/new
