### ISSUE TITLE
no https

### ISSUE THREAD

**Issue by mikeyb** [ethereumclassic/etherwallet#3]
We should probably setup ssl connections

**Comment by elaineo** [comment]
This was originally going to migrate to another server, which is why we were holding off on it, but it looks like that's not gonna happen so I'll take care of this.

**Comment by mikeyb** [comment]
The community has some funding available. ETC should look into hosting some of the original sites with some of these funds.

Specifically, I think it would be a good idea to have a marketing, wallet & block explorer funded multi server setup in a single and easy to manage environment along with ssl certificates for them for long term. 

Obviously this is out of scope for this issue, just thought it was worth mentioning.

**Comment by elaineo** [comment]
@mikeyb I agree with that. I actually don't mind the cost of hosting, and I know corey is also donating etherhub.io as a server for ETC services. 

The bigger problem is that we need someone who is actually willing to take the time to set up a single and easy to manage environment for multiple services. Hmm, will follow up on slack where it's more appropriate.

**Comment by elaineo** [comment]
heh, finally set up new server and added an ssl cert. that only took friggin forever.
