### ISSUE TITLE
SyntaxError: Unexpected keyword 'const'.

### ISSUE THREAD

**Issue by whilei** [ethereumclassic/etherwallet#32]
I'm getting what looks like the result of a syntax error. Maybe.

- tabs missing (or un-generated), 
- alert bar on bottom always open
- visible un-interpolated dynamic html vals `{{value.name}}`
- "Success! Your wallet has been generated!" on landing

Console error log:
```
etherwallet-master.js:1262 SyntaxError: Unexpected keyword 'const'. Const declarations are not supported in strict mode.
```

![screen shot 2017-06-02 at 06 28 06](https://cloud.githubusercontent.com/assets/10228550/26724013/d1d59630-475c-11e7-9360-13a235577b80.png)

**Browser**: Safari
https://ethereumproject.github.io/etherwallet/

**Comment by elaineo** [comment]
oops! thanks, i didn't realize that safari does not support `const`

**Comment by elaineo** [comment]
fixed with https://github.com/ethereumproject/etherwallet/commit/f5061a867b7af7e0739a209df4417d9ded48f193
