### ISSUE TITLE
Wallet leaves zero! HELPME PLEASE,  Several days of work to mine (5 days)

### ISSUE THREAD

**Issue by RAIBENMINERGOLD** [ethereumclassic/etherwallet#35]
When I got into my wallet, I saw that it was all to zero! Please help me, this discourages me .. I am new and stopped mining .. I had many hopes and confidence in this project. I hope you can help me to continue to undermine and recover my hopes, a big hug! Rubén
![balance traspaso](https://cloud.githubusercontent.com/assets/29221196/26817283/42aa07b0-4a96-11e7-8487-84f01a92a459.jpg)
![traspaso pg ether](https://cloud.githubusercontent.com/assets/29221196/26817315/5ec5acec-4a96-11e7-935d-9d1f94219f52.jpg)
![cuenta a cero](https://cloud.githubusercontent.com/assets/29221196/26817325/6963faa0-4a96-11e7-8a53-5a27e1e2c096.jpg)

**Comment by elaineo** [comment]
you are looking at a different address between the first image and the last one.

**Comment by RAIBENMINERGOLD** [comment]
That big mistake of mine .. I got confused with the key of ETHEREUM .. thank you very much. A hug!
