### ISSUE TITLE
New Favicon

### ISSUE THREAD

**Issue by ChuckSRQ** [ethereumclassic/etherwallet#40]
![favicon-16x16](https://user-images.githubusercontent.com/20735086/26998694-c9f14e6a-4d55-11e7-82de-a2bed6fc77de.png)

**Comment by elaineo** [comment]
ok: https://github.com/ethereumproject/etherwallet/commit/41234711798caf246c290e16cb33fe40c18eb968

It would be nice to have this in other sizes too for different devices. 

```html
  <link rel="apple-touch-icon" sizes="60x60" href="images/fav/apple-touch-icon-60x60.png">
  <link rel="apple-touch-icon" sizes="76x76" href="images/fav/apple-touch-icon-76x76.png">
  <link rel="apple-touch-icon" sizes="120x120" href="images/fav/apple-touch-icon-120x120.png">
  <link rel="apple-touch-icon" sizes="152x152" href="images/fav/apple-touch-icon-152x152.png">
  <link rel="apple-touch-icon" sizes="180x180" href="images/fav/apple-touch-icon-180x180.png">
  <link rel="icon" type="image/png" href="images/fav/favicon-32x32.png" sizes="32x32">
  <link rel="icon" type="image/png" href="images/fav/favicon-194x194.png" sizes="194x194">
  <link rel="icon" type="image/png" href="images/fav/favicon-96x96.png" sizes="96x96">
  <link rel="icon" type="image/png" href="images/fav/android-chrome-192x192.png" sizes="192x192">
  <link rel="icon" type="image/png" href="images/fav/favicon-16x16.png" sizes="16x16">`

**Comment by ChuckSRQ** [comment]
Okay will make them.

**Comment by ChuckSRQ** [comment]
![favicon16x16](https://user-images.githubusercontent.com/20735086/27004073-1779cef2-4dd1-11e7-919d-9198d3daf293.png)
![favicon32x32](https://user-images.githubusercontent.com/20735086/27004074-177b5772-4dd1-11e7-9b16-95a76a8f3fdb.png)
![favicon48x48](https://user-images.githubusercontent.com/20735086/27004075-177c666c-4dd1-11e7-902d-21d10063fd13.png)
![favicon64x64](https://user-images.githubusercontent.com/20735086/27004076-177cb37e-4dd1-11e7-9a6b-7b9c2c9ffe87.png)
![favicon128x128](https://user-images.githubusercontent.com/20735086/27004077-177d2bce-4dd1-11e7-981a-095eb570c881.png)

Will these work? This 16x16 is a little more visible.

**Comment by elaineo** [comment]
sure just upload in this dir: https://github.com/ethereumproject/etherwallet/tree/gh-pages/images/fav
