### ISSUE TITLE
New Top Banner Color instead of Red

### ISSUE THREAD

**Issue by ChuckSRQ** [ethereumclassic/etherwallet#41]
Green HTML Color #30B332

**Comment by elaineo** [comment]
ok: https://github.com/ethereumproject/etherwallet/commit/682835a58e6d4ecc12ffbfaea12f2bc8d0780a58

**Comment by ChuckSRQ** [comment]
Can we have same color for this?
![image](https://user-images.githubusercontent.com/20735086/27007907-5c891a60-4e31-11e7-98ae-a5cb9bccd194.png)
