### ISSUE TITLE
How long until transfers show up in new wallet?

### ISSUE THREAD

**Issue by mtbiker98** [ethereumclassic/etherwallet#43]
I created a new wallet and then sent 2 U.S. dollars worth of ETC over to it as a test transfer from my Coinbase account.  After about 5 minutes or so the transfer cleared from the Coinbase account.  But it's now been 30 minutes and the ETC amount has not shown up yet in my new ETC Wallet.  
Is this normal or is there a problem?  
I also have noticed (I am new here) that the link to find my transaction history did not work.  I then tried to go to the main site URL and it shows as down right now with 503 Service Unavailable:   http://etherhub.io/

**Comment by elaineo** [comment]
the balance should update within a minute. try gastracker.io if the etherwallet node is not updating

**Comment by mtbiker98** [comment]
Hi Elaine, how are you?
 
Thanks for getting back to me.  I think I figured out the issue about 2 hours later...maybe you can tell me if I'm correct.
 
So I kept looking at my Coinbase account and the "test" 2 dollar "ETH" transfer to my etherwallet definitely went through, but was still not showing up on the other end.
 
I eventually found after all kinds of digging around on the 'ol interwebs ;-)  that Coinbase made an announcement at the end of 2016 that they would no longer perform transactions in "ETC"......"ah hah!", I thought.  haha
 
So it seems I was confused by this etherwallet and didn't understand that there are 2 types of ether (tell me if I'm wrong), either ETC (classic) or ETH (the current "thing" haha).
 
I think for some reason Coinbase transferred the 2 dollars of ETH outbound (or maybe took it for themselves??? haha) and/or it just disappeared, because it still hasn't shown up in my new "ETC" wallet which isn't "ETH".
 
Lemme know if that's sounds about right to you or if I'm way off.  Obviously I'm fairly new at all this even though I first started out buying very small amounts of BTC 3 years ago when I created a Coinbase account and a Blockchain wallet.  I had no clue what I was doing and 3 years later after lots of reading and listening to 100's of interviews and podcasts about all this I still feel like I can't explain it very well or convincingly enough to friends and family.  None of whom have yet to open accounts anywhere and buy some BTC or ETH or whatever yet.
 
That's how I know this stuff isn't in a "bubble" or going away.  Absolutely everyone I know up to this point don't know anything about cryptos and don't have accounts or "own" any online of offline.  And my inability to explain it technically or properly at a layman's level (or even high level! haha) is probably keeping them from getting in and remaining skeptical about it. 
 
I feel they are missing the train as it leaves the station at this point. 
 
Anyways...long story longer :)  I'm just really glad I didn't do worse than losing 2 dollars worth.  I was so close to transferring half of my ETH on the first try before I stopped myself at the last second and just did 2 dollars instead. 
 
Wish I woulda done just 1 dollar though.  hahaha
 
Well, thanks much again for getting back to me.  If you have any idears or wanna tell me if I'm kinda right or not about what may have happened, please do.  I would like to know if possible and learn more so if I am talking to anyone again about this I can at least inform them of something like this so they don't make the same mistake that I did.
 
Take care,
 
Ian Curran
Tampa, FL


-----Original Message-----

**Comment by ChuckSRQ** [comment]
Hi Ian, 

I actually live in Tampa as well and I do help people in the area become more familiar with crypto currencies. 

Yes, there are two Ethereums. Ethereum and Ethereum Classic. It's a long story. Luckily for you, the address you made exists on both blockchains. It also has the same key. So if you sent ETH to it instead of ETC, you probably have a high chance of recovering it.. 

Go to https://myetherwallet.com.  Upload the key. You should see the ETH.  https://classicetherwallet.com is for ETC.  

If you would like to get into contact for me to learn more. Please feel free to call or text at 941-223-4936 or email me at carlos.r.graterol@gmail.com
  
Carlos Graterol
Marketing Manager at ETC Dev Team
