### ISSUE TITLE
no ethereum sent

### ISSUE THREAD

**Issue by lifeagle** [ethereumclassic/etherwallet#44]
I sent ethereum classic to another wallet and it never showed up. 
then i tried to see my transactions and that page wont load.

**Comment by lifeagle** [comment]
this was money i was saving for my children and i feel i got ripped off

**Comment by lifeagle** [comment]
Address 0x6c6d5d866d on Ethereum Classic
Addr Details
Address
0x6c6d5d866da7c4c2e774bfadb6b3f4a1d0c2507b
Type
STANDARD ADDRESS
Balance
5.0000 ether
 
5000000000000000000 Wei
 
$103.90
HardFork Balance
0.0000 ether

Recent Transactions
Unconfirmed Fresh transaction, have less than 12 confirmations
Recent Recent transaction OUT Outcoming transaction
IN Incoming transaction
CALL Contract execution
FAILED At least one of contract transfers failed to execute
Block	Confirmations	Timestamp	Tx Hash	Type	Value	To / From
3929966	5160	17 Jun 2017, 07:08	0x4efcf8ad	IN	5.0000 ether	 0x05b34ee3fec3586a8e0bb0b518f84e6c6fd9e9b6
Gas Tracker does display all transactions made in Classic Ethereum blockchain since block 1920000 (the moment of TheDAO Hard Fork).

**Comment by elaineo** [comment]
you can see your transaction right here: http://gastracker.io/tx/0x0bf71fd8c6c60aad2ba1c1c64361c518ad9b3b5db3b59c412497f36f67366c1a
