### ISSUE TITLE
Etherwallet page loading and loading.... 

### ISSUE THREAD

**Issue by Hoff40** [ethereumclassic/etherwallet#45]
Hi,

If someone can help me with this problem.. 
When I unlock my etherwallet I can't see how many ETC I have. The account balance is stuck on 'loading'.. 
Also the page freezes and keeps on loading.. 

I use safari web browser with: https://classicetherwallet.com

**Comment by elaineo** [comment]
server had some memory issues. restarted it, pls try again

**Comment by Hoff40** [comment]
still not working :(
