### ISSUE TITLE
transaction doesnt show in account balance

### ISSUE THREAD

**Issue by jcmhemert** [ethereumclassic/etherwallet#46]
it's been 30 minutes since a succesful transaction. No change in account balance is visible in Chrome or Firefox.

**Comment by elaineo** [comment]
do you see the account balance in a block explorer like gastracker.io?

**Comment by jcmhemert** [comment]
I only see a hardfork balance which is correct.

**Comment by elaineo** [comment]
so it's working then?

**Comment by jcmhemert** [comment]
I guess. :) As I said I’m new and have to find out what the heck it means. No wories though. I’m eager to learn. Thanks for your help.

 

Van: Elaine Ou [mailto:notifications@github.com] 
Verzonden: zaterdag 24 juni 2017 06:41
Aan: ethereumproject/etherwallet <etherwallet@noreply.github.com>
CC: jcmhemert <jjcmvanhemert@gmail.com>; Author <author@noreply.github.com>
Onderwerp: Re: [ethereumproject/etherwallet] transaction doesnt show in account balance (#46)

 

so it's working then?
