### ISSUE TITLE
When I log into my wallet my the balance does not load.

### ISSUE THREAD

**Issue by jessecurell** [ethereumclassic/etherwallet#47]
When I log into my wallet my the balance does not load. I used etherhub.io to make sure my funds made it to the address I was given with the wallet and it says they are there. At this point I just want to get my etc out of this address so I can use a wallet that actually works. Can someone tell me the easiest way of getting my money out of this wallet.

**Comment by realcodywburns** [comment]
Load your wallet file in myetherwallet.com and use the `etc node(epool)` at the top right
