### ISSUE TITLE
ETC sent to pOLONIEX  but not received at exchange

### ISSUE THREAD

**Issue by undergroundbase** [ethereumclassic/etherwallet#48]
ETC sent but not received at exchange

Will I get the funds back? If so, how long will that normally take?

Thanks

iTS BEEN OVER 6 HOURS

**Comment by elaineo** [comment]
Duplicate: https://github.com/ethereumproject/etherwallet/issues/29

**Comment by undergroundbase** [comment]
Issue still not been resolved

**Comment by splix** [comment]
@undergroundbase what response did you get from Poloniex? https://poloniex.freshdesk.com/support/tickets/new

**Comment by HOZAN85** [comment]
@splix i have same problem  

the Etc explorer shows that Transaction Etc from STANDARD ADDRESS 0x0eeeda0e56781b2ca310e17c57a6380bb838b9b3 
to contract adress 0xb09cbe4f7e845184d8c6e4607cd816bfc9bc08d3 failed
what can we do ?
i answer from poloniex support i had sent them at 1 july

**Comment by HOZAN85** [comment]
@splix 
no answer from polineix support
