### ISSUE TITLE
Just had my wallet stolen

### ISSUE THREAD

**Issue by smokeyta** [ethereumclassic/etherwallet#49]
Just checked my wallet and had 6.64549029250476208 ETC transfered out of my wallet. while I ate dinner. this was sent to 0xdaa10e89d63419905de4cb727a31e1a9cb058070. Will have to stop using this wallet and let people know this is not a safe wallet to use
hash	0x34a3f6721b211488892ac3c24a59159c9ebbcee702430f2510fcd04020d0a5af
blockNumber	4003383
Time	2017-06-29 17:55:39 -0400 (1 hour, 9 mins ago)
from	My Wallet
to	0xdaa10e89d63419905de4cb727a31e1a9cb058070
value	6.64549029250476208 ETC
gas Provided	21000
gasPrice	21000000000
nonce	1

**Comment by realcodywburns** [comment]
Unable to duplicate.  Which website were you accessing classicetherwallet from?

**Comment by smokeyta** [comment]
https://classicetherwallet.com/
Using Chrome 
But I also had the local copy which shows the transaction was made.

**Comment by smokeyta** [comment]
http://etherhub.io/addr/0xdaa10e89d63419905de4cb727a31e1a9cb058070 block 4003383. I will move to a hardware wallet just wanted to let people know that classic ethereum classic wallet is not safe to use.

**Comment by realcodywburns** [comment]
The domain classicetherwallet.com has been hijacked. We are investigating further

**Comment by stupci** [comment]
Sent 21 etc to kraken verify the address but etc has sent to other address 
0xf065e4df0a9215e400718c398d9094faa6cb085c
I type 15.1 etc to sent I don't know what happen.TX ID 0x1ec02fcf014091f6c3491dd80cbba4eafa507ab6280b79416ff9ad190e2fe3be

**Comment by kisser228** [comment]
My wallet was stolen as well. 

Transaction Details
Timestamp
Jun 29, 2017 6:56 PM
Value
1327.9796 ether
 
1327979559000000000000 Wei
 
$23,903.63
 
 
Hash
0xb8d3b6ee453b0d4841b53532e69677da0868b17474ee237abdf10d4c06e684ad
NOnce
0
From
0x4c6c1e80e06550e7b5f58e19c012ec8a09dd67c5
To
0x2b8cc0d2901a04145c86c7ae22ca649f974f0e34
 
 
Block Height
4004410
Block Hash
0xca586dd3b6c9ed0d684919ad301307f98a87cc81dffdfb7a3336fe323bde3c6c
Gas Provided
21000
Gas Used
21000
Gas Price
21000 Mwei

**Comment by motoroto** [comment]
Does this affect only people who use the wallet on the website? What about users that download and only use the files locally? In that case, are there still dependencies on the hijacked domain?

**Comment by pyskell** [comment]
Pulling directly from this repository and using locally/offline is fine. 

Cloning the classicetherwallet.com website would still leave you at risk.

**Comment by Sjors** [comment]
> Pulling directly from this repository and using locally/offline is fine.

Not unless you're sure the GitHub account wasn't compromised and force-pushed over.
