### ISSUE TITLE
Just had all my ETC STOLEN from classicetherwallet.com

### ISSUE THREAD

**Issue by kisser228** [ethereumclassic/etherwallet#51]
I have the hash # and the destination address. I want it returned!!!

Transaction Details
Timestamp
Jun 29, 2017 6:56 PM
Value
1327.9796 ether
 
1327979559000000000000 Wei
 
$23,903.63
 
 
Hash
0xb8d3b6ee453b0d4841b53532e69677da0868b17474ee237abdf10d4c06e684ad
NOnce
0
From
0x4c6c1e80e06550e7b5f58e19c012ec8a09dd67c5
To
0x2b8cc0d2901a04145c86c7ae22ca649f974f0e34
 
 
Block Height
4004410
Block Hash
0xca586dd3b6c9ed0d684919ad301307f98a87cc81dffdfb7a3336fe323bde3c6c
Gas Provided
21000
Gas Used
21000
Gas Price
21000 Mwei

**Comment by smokeyta** [comment]
I'm pretty sure this is the account that they are sending the stolen coins to http://etherhub.io/addr/0x8837234b8d27cf4abdae353264f45c8866631ed5

**Comment by medolino2009** [comment]
hi, my ether classic also stolen : http://gastracker.io/addr/0x1174C30E1B14842F482666d7AaD3d9E476B69215
Block: 4002608
Confirmations: 6975
29 Jun 2017, 06:55
From my adres: 0x1174c30e1b14842f482666d7aad3d9e476b69215
TX Hash: 0xbcd93931
43.0866 ether
all gone to this adres: 0xce52bfaf3f4900fecfbf43b8da2890cf59cab323
from that adres all transfered to this adres: 0x6c73962cbfda97ac8867499f1116b7e1b5d310d7
Is there any way to get it back ? i don't get it... is it really so unsafe this ether classic ???????????
Everything my machines did for one month is gone.... i really hope someone can get it back for me...
Please send it to this adres if possible: 0xa931c2ebcbc6dde30ad93efc57c639e67871c6d4 (i already sent 2 ether classics that were mined today to this new adres)
total : 43.0866 ether
I really hope to get it again.... 43 ether is maybe not much for someone but it is very much for me...
I really hope this system is not made in the way that something like this can be done and person that stole it get away with it....come on....
Thanx in advance
best regards
Miki

**Comment by xPathin** [comment]
Just if anyone cares, can confirm: 0x8837234b8d27cf4abdae353264f45c8866631ed5 is where everything is going to.
