### ISSUE TITLE
ETC Account Hacked

### ISSUE THREAD

**Issue by WoodaMooda** [ethereumclassic/etherwallet#53]
Culprit address: 0x47fcff82e3e901280fd034bc216588080438ba34

Any way to trace this address through exchanges?

**Comment by kisser228** [comment]
Probably the same person at this address...

0x2b8cc0d2901a04145c86c7ae22ca649f974f0e34

Trace it

**Comment by WoodaMooda** [comment]
TY for the address!
Hard to say, all I know is I want my 201 ETC's back, and classicetherwallet better take care of this problem, asap.

**Comment by WoodaMooda** [comment]
Dear classiceatherwallet.com,

My funds were stlen and I expect a timely refund ASAP.

Thank you in advance!

------------------------------

Timestamp
Jun 29, 2017 7:53 PM
Value
200.9996 ether
 
200999559000000000000 Wei
 
$3,573.77
 
 
Hash
0x3448e11c5b321850edb84cb6e46892449b055be5631d9ff3fc577fc529995b91
NOnce
0
From
0xbccf7ab738df7011b9ad66172b8b639dcf975348
To
0x47fcff82e3e901280fd034bc216588080438ba34
 
 
Block Height
4004664
Block Hash
0xc937bc7d9f6bc9f2d4426ec308cd33231943997768f6853f49403a5b0e2443fb
Gas Provided
21000
Gas Used
21000
Gas Price
21000 Mwei

**Comment by medolino2009** [comment]
hi, my ether classic also stolen : http://gastracker.io/addr/0x1174C30E1B14842F482666d7AaD3d9E476B69215
Block: 4002608
Confirmations: 6975
29 Jun 2017, 06:55
From my adres: 0x1174c30e1b14842f482666d7aad3d9e476b69215
TX Hash: 0xbcd93931
43.0866 ether
all gone to this adres: 0xce52bfaf3f4900fecfbf43b8da2890cf59cab323
from that adres all transfered to this adres: 0x6c73962cbfda97ac8867499f1116b7e1b5d310d7
Is there any way to get it back ? i don't get it... is it really so unsafe this ether classic ???????????
Everything my machines did for one month is gone.... i really hope someone can get it back for me...
Please send it to this adres if possible: 0xa931c2ebcbc6dde30ad93efc57c639e67871c6d4 (i already sent 2 ether classics that were mined today to this new adres)
total : 43.0866 ether
I really hope to get it again.... 43 ether is maybe not much for someone but it is very much for me...
I really hope this system is not made in the way that something like this can be done and person that stole it get away with it....come on....
Thanx in advance
best regards
Miki

**Comment by elaineo** [comment]
https://github.com/ethereumproject/etherwallet/issues/62
