### ISSUE TITLE
BALANCE 0!!!!

### ISSUE THREAD

**Issue by filippo2658** [ethereumclassic/etherwallet#55]
![schermata 2017-06-30 alle 09 20 12](https://user-images.githubusercontent.com/21193656/27725197-7ef9090e-5d75-11e7-9b73-e2750f876377.png)
Just up I found an email from ethereumslack.com that warned me not to use it
Etherclassicwallet because it had been hacked ... the news is that I used it just in the evening before going to bed .... I rushed immediately on myetherwallet with switch on ETC and MY BALANCE IS A 0 ... .I can provide personal data including my JSDN key in order to demonstrate the addressability of the address:
0x2a52a7b1BcA668D6B1140D81E19aff88606d87db ... I am 1202 ETC .... guys I have much respect for the work you do and I believe in the project ... I have invested part of my savings .... I am even asking you to do something ...
![schermata 2017-06-30 alle 07 39 39](https://user-images.githubusercontent.com/21193656/27725001-b5520b8c-5d74-11e7-814e-0d4881c251ea.png)

**Comment by medolino2009** [comment]
hi, my ether classic also stolen : http://gastracker.io/addr/0x1174C30E1B14842F482666d7AaD3d9E476B69215
Block: 4002608
Confirmations: 6975
29 Jun 2017, 06:55
From my adres: 0x1174c30e1b14842f482666d7aad3d9e476b69215
TX Hash: 0xbcd93931
43.0866 ether
all gone to this adres: 0xce52bfaf3f4900fecfbf43b8da2890cf59cab323
from that adres all transfered to this adres: 0x6c73962cbfda97ac8867499f1116b7e1b5d310d7
Is there any way to get it back ? i don't get it... is it really so unsafe this ether classic ???????????
Everything my machines did for one month is gone.... i really hope someone can get it back for me...
Please send it to this adres if possible: 0xa931c2ebcbc6dde30ad93efc57c639e67871c6d4 (i already sent 2 ether classics that were mined today to this new adres)
total : 43.0866 ether
I really hope to get it again.... 43 ether is maybe not much for someone but it is very much for me...
I really hope this system is not made in the way that something like this can be done and person that stole it get away with it....come on....
Thanx in advance
best regards
Miki

**Comment by elaineo** [comment]
https://github.com/ethereumproject/etherwallet/issues/62
