### ISSUE TITLE
ether classic  Transaction failed on poloniex

### ISSUE THREAD

**Issue by HOZAN85** [ethereumclassic/etherwallet#60]
hello
the Etc explorer shows that Transaction Etc from STANDARD ADDRESS 0x0eeeda0e56781b2ca310e17c57a6380bb838b9b3 
to contract adress 0xb09cbe4f7e845184d8c6e4607cd816bfc9bc08d3 failed
I realized the block 4018208 has 2 Transaction  failed
what can we do ?

**Comment by ChuckSRQ** [comment]
Probably because the transaction did not have enough GAS.
