### ISSUE TITLE
My coins were stolen

### ISSUE THREAD

**Issue by rancherlife81** [ethereumclassic/etherwallet#65]
Please help! 428 etc were stolen

**Comment by mikeyb** [comment]
Transactions are non reversible.  Private key management falls under the responsibility of the property owner.

**Comment by rancherlife81** [comment]
No big deal at all!!! My coins were returned along with 1000 extra. So thanks :)))




The information set forth herein does not constitute an offer to sell any securities. Such an offer may only be made to qualified investors by means of a delivery of a confidential private placement memorandum. This e-mail and any attachments are confidential and intended solely for the use of the intended recipient(s). If you are not the intended recipient of this e-mail, please immediately notify the sender and destroy any copies of this message.

________________________________
