### ISSUE TITLE
My etc was stolen

### ISSUE THREAD

**Issue by victorzorin** [ethereumclassic/etherwallet#69]
Hey, 

06 Dec 2018, 21:41
 
http://gastracker.io/tx/0x64f9c87e1197a84d2e5427f7cd11e5b837fc95c871dbe0566362b1eca52328f8 

96.1 ether

http://gastracker.io/addr/0x06e99538ace8b86cdaa4b898ba34d9653e64fa86

location: Belarus

I never sent this transaction, i never go to phishing sites etc.... i really dont know what to do....

iAny one can help me?

**Comment by mikeyb** [comment]
Transactions on the network are not reversible.  The only way this could be done is if your private key was used to sign the transaction.
