### ISSUE TITLE
Web extension breakout

### ISSUE THREAD

**Issue by realcodywburns** [ethereumclassic/etherwallet#7]
I would like to develop the web extensions, chrome and firefox as a separate project.  I think they are a more valuable project alone than bundled with the paper wallet creator. The need for a stand alone api is also needed.

**Comment by mikeyb** [comment]
Sounds like a solid idea to me.  I would probably package the extensions separately into their own npm packages and require them as dependencies in package.json

There is a lot of code in this repo dependent on the chrome extension code so make sure to keep things working.

**Comment by elaineo** [comment]
This is the new repo for the chrome extension, right? https://github.com/realcodywburns/ETC-CX-Wallet
